name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd apps/api
          npm install

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
        run: |
          npm install -g vercel
          cd apps/api
          vercel deploy --prod --token=$VERCEL_TOKEN