name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd apps/web
          npm install

      - name: Debug Environment Variables
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}"
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}"
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}"
        shell: bash

      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      - name: Verify Current Directory
        run: |
          pwd
          ls -la

      - name: Deploy to Vercel
        run: |
          cd apps/web
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --debug
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
