name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd apps/web
          npm install

      - name: Debug Environment Variables
        run: |
          echo "VERCEL_TOKEN=$VERCEL_TOKEN"
          echo "VERCEL_ORG_ID=$VERCEL_ORG_ID"
          echo "VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_FRONTEND"
        # Adicione uma verificação de falha se as variáveis não estiverem definidas
        shell: bash
        continue-on-error: false

      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
        run: |
          cd apps/web
          vercel deploy --prod --token=$VERCEL_TOKEN
